#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "Components/ActorComponent.h"
#include "../../NaGlobalHeader.h"
#include "NaMobInputComponent.generated.h"

/**

	This is a common input interface of all mobs, both from AI and player controller.
	This component includes an input receiver and an input sender.
	Input receiver receives input events generated by a "thinking" method of the mob, usually from the controller.
	Input sender delivers the input signal to the mob's action module to trigger the real action.
	Therefore this class is just a signal transferer from controller to the action module. Also it provides interface to player input. 

	Default enabled action:
	MoveForward, MoveRight(axis);
	Jump;

*/




UCLASS()
class NAPACK_API UNaMobInputComponent : public UActorComponent {

	GENERATED_BODY()

public:

	UNaMobInputComponent();

	// A default function doing nothing. For initializing.
	void NullAxis(float scale) { return; };
	void NullAction() { return; };

	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	
	// Add a default this component into a mob
	static UNaMobInputComponent* AddDefault(class ANaMob* Parent, FName Name = TEXT("MobInputComponent"));


	/* Axis */

	/**
	Axis has a value which will be read every tick. When receiving axis input, the value will be updated. What to do with this value is defined by function pointer.
	*/
	float MoveForwardAxisValue = 0.f;
	void TakesMoveForward(float val);			// Call by controller to give an input move forward axis value
	DECLARE_DELEGATE_OneParam(DoMoveForward, float);			// Defines what to do with axis value tickly
	void SendMoveForward(float val);		// Execute 
	



};

// Macros to declare a new axis or action in the component
/*
#define MOB_INPUT_AXIS(Name) \
	float NameAxisValue = 0.f;\
	void TakeName(float val){NameAxisValue=val;};\			
	DECLARE_DELEGATE_OneParam(DoName, float);\
	void SendName(float val) { DoName.ExecuteIfBound(); }; \
	
	