#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "Engine/EngineTypes.h"
#include "Components/ActorComponent.h"
#include "../../NaGlobalHeader.h"
#include "NaMobInputComponent.generated.h"

/**

	This is a common input interface of all mobs, both from AI and player controller.
	This component includes an input receiver and an input sender.
	Input receiver receives input events generated by a "thinking" method of the mob, usually from the controller.
	Input sender delivers the input signal to the mob's action module to trigger the real action.
	Therefore this class is just a signal transferer from controller to the action module. Also it provides interface to player input. 
	Must connect with a NaMob.

	Default enabled action:
	MoveForward, MoveRight(axis);
	Jump;

*/




UCLASS()
class NAPACK_API UNaMobInputComponent : public UActorComponent {

	GENERATED_BODY()

public:

	UNaMobInputComponent();

	// A default function doing nothing. For initializing.
	void NullAxis(float scale) { return; };
	void NullAction() { return; };

	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	
	// Add a default this component into a mob
	static UNaMobInputComponent* AddDefault(class ANaMob* Parent, FName Name = TEXT("MobInputComponent"));


	/* Axis */

	/**
	Axis has a value which will be read every tick. When receiving axis input, the value will be updated. What to do with this value is defined by a delegate.
	*/

	DECLARE_DELEGATE_OneParam(FMobInputAxisSignature, float);

	float MoveForwardAxisValue = 0.f;
			// Defines what to do with axis value tickly
	void SendMoveForward(float val) { DoMoveForward.ExecuteIfBound()};		// Execute 
	void TakeMoveForward(float val) { MoveForwardAxisValue = val; };		// Call by controller to give an input move forward axis value
	
	/* Action */

	DECLARE_DELEGATE(FMobInputActionSignature);

	
	FMobInputActionSignature DoJump;
	void SendJump() { DoJump.ExecuteIfBound(); };
	void TakeJump() { SendJump(); };

};

// Macros to declare a new axis or action in the component
/*
#define MOB_INPUT_AXIS(Name) \
	float NameAxisValue = 0.f;\		
	FMobInputAxisSignature DoName;\
	void SendName(float val) { DoName.ExecuteIfBound(); }; \
	void TakeName(float val){ NameAxisValue=val; };\		

#define MOB_INPUT_ACTION(Name) \
	FMobInputActionSignature DoName;
	void SendName(){DoName.ExecuteIfBound();}
