#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/ShapeComponent.h"
#include "Components/BoxComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/SphereComponent.h"
#include "../../NaGlobalHeader.h"
#include "NaMobSkillCollision.generated.h"

/* Mob Skill Collision is a shape component (collision body) generated by Mob Skill to detect the collsion and send hit result to skill actor. */

class ANaMob;
class ANaMobSkill;

UENUM()
enum class ESkillCollisonShape :uint8 {
	SCS_Sphere	UMETA(DisplayName = "Sphere"),
	SCS_Capsule	UMETA(DisplayName = "Capsule"),
	SCS_Box 	UMETA(DisplayName = "Box")
};

UCLASS(BlueprintType)
class NAPACK_API ANaMobSkillCollision :public AActor {

	GENERATED_BODY()

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:

	ANaMobSkillCollision();

	// Construction script
	virtual void OnConstruction(const FTransform & trans) override;

	// Called every frame
	virtual void Tick(float DeltaTime) override;

protected:

	ANaMobSkill* SourceSkill;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	ESkillCollisonShape CollisionShape = ESkillCollisonShape::SCS_Capsule;




};

