#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "../../NaGlobalHeader.h"
#include "NaMobSkillCollision.generated.h"

/* Mob Skill Collision is a shape component (collision body) generated by Mob Skill to detect the collsion and send hit result to skill actor. */

class ANaMob;
class ANaMobSkill;
class USceneComponent;
class UShapeComponent;
class UBoxComponent;
class UCapsuleComponent;
class USphereComponent;
class UPrimitiveComponent;

UENUM()
enum class ESkillCollisonShape :uint8 {
	SCS_Sphere	UMETA(DisplayName = "Sphere"),
	SCS_Capsule	UMETA(DisplayName = "Capsule"),
	SCS_Box 	UMETA(DisplayName = "Box")
};

USTRUCT(BlueprintType)
struct FSkillCollisionHitReturn {

	GENERATED_USTRUCT_BODY()

public:

	FSkillCollisionHitReturn(
		ANaMobSkillCollision* InSourceCollision,
		AActor* InOtherActor,
		UPrimitiveComponent* InOtherComponent,
		FVector InNormalImpulse,
		const FHitResult & InHitResult
	);

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	ANaMobSkillCollision* SourceCollision;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	AActor* OtherActor;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	UPrimitiveComponent* OtherComponent;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FVector NormalImpulse;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FHitResult HitResult;

};

UCLASS(BlueprintType)
class NAPACK_API ANaMobSkillCollision :public AActor {

	GENERATED_BODY()

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:

	ANaMobSkillCollision();

	// Construction script
	virtual void OnConstruction(const FTransform & trans) override;

	// Called every frame
	virtual void Tick(float DeltaTime) override;

protected:

	ANaMobSkill* SourceSkill;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	ESkillCollisonShape CollisionShape = ESkillCollisonShape::SCS_Capsule;

	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	FName SocketName;
	

	/* Generating */

public:

	/** Make a collision from a skill.
	* @Param SourceSkill The skill owning this collision.
	* @Param Class Applied skill collision class.
	* @Param InTransform Relative transform.
	* @Param AttachToComponent Component this collision should attach. If this param is left null, skill will attach to the root component.
	* @Param SocketName Socket of attachment of this skill.
	* @Param DoAttachment If set false, the skill actor will not attach to anything and generate with world transform.
	*/
	static ANaMobSkillCollision* MakeCollisionByClass(
		ANaMobSkill* SourceSkill,
		TSubclassOf<ANaMobSkillCollision> Class,
		const FTransform & InTranform,
		USceneComponent* AttachToComponent = nullptr,
		FName SocketName = NAME_None,
		float LifeSpan = 0.f,
		bool DoAttachment = true
	);

	void Destroyed() override;

	/* Collision detecting */

	// Called when hit detected.
	void SendHit(const FSkillCollisionHitReturn & Data);

protected:

	virtual void SendHitDelegateFunc(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, FVector NormalImpulse, const FHitResult & HitResult);

	TSet<AActor*> AlreadyHitActors;

};

