#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "../../NaGlobalHeader.h"
#include "NaMobSkillCollision.generated.h"

/* Mob Skill Collision is a shape component (collision body) generated by Mob Skill to detect the collsion and send hit result to skill actor. */

class ANaMob;
class ANaMobSkill;
class USceneComponent;
class UShapeComponent;
class UBoxComponent;
class UCapsuleComponent;
class USphereComponent;
class UPrimitiveComponent;
class UStaticMeshComponent;
class UStaticMesh;

UENUM()
enum class ESkillCollisionShape :uint8 {
	SCS_Sphere	UMETA(DisplayName = "Sphere"),
	SCS_Capsule	UMETA(DisplayName = "Capsule"),
	SCS_Box 	UMETA(DisplayName = "Box"),
	SCS_StaticMesh UMETA(DisplayName = "StaticMesh")
};

USTRUCT(BlueprintType)
struct FSkillCollisionHitReturn {

	GENERATED_USTRUCT_BODY()

public:

	FSkillCollisionHitReturn();

	FSkillCollisionHitReturn(
		ANaMobSkillCollision* InSourceCollision,
		UPrimitiveComponent* HitComponent,
		AActor* InOtherActor,
		UPrimitiveComponent* InOtherComponent,
		FVector InNormalImpulse,
		const FHitResult & InHitResult
	);

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	ANaMobSkillCollision* SourceCollision;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	UPrimitiveComponent* HitComponent;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	AActor* OtherActor;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	UPrimitiveComponent* OtherComponent;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FVector NormalImpulse;

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FHitResult HitResult;

};

UCLASS(BlueprintType)
class NAPACK_API ANaMobSkillCollision :public AActor {

	GENERATED_BODY()

protected:

	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:

	ANaMobSkillCollision();

	// Construction script
	virtual void OnConstruction(const FTransform & trans) override;

	// Called every frame
	virtual void Tick(float DeltaTime) override;

protected:

	/** Root scene component of collision actor. 
	* As the class of collision body is flexible, it will not be displayed in the panel.
	* To get the collision body, use the function "GetCollision()". 
	*/
	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	USceneComponent* Root;

	// Parent of the collision component.
	// Set transform of this component to adjust collision's transform, as the collision component is not visible in blueprint.
	UPROPERTY(BlueprintReadOnly, EditAnywhere)
	USceneComponent* CollisionRoot;

	// Collision component
	UPrimitiveComponent* Collision;

	ANaMobSkill* SourceSkill;

	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "MobSkillCollision|Shape")
	ESkillCollisionShape CollisionShape = ESkillCollisionShape::SCS_Capsule;

	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "MobSkillCollision")
	FName SocketName;
	
	/* Transform */

	// Box half X size, capsule radius or sphere radius. Invalid for static mesh.
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "MobSkillCollision|Shape")
	float HalfSizeX = 8.f;

	// Box half Y size. Invalid for non-box.
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "MobSkillCollision|Shape")
	float HalfSizeY = 8.f;

	// Box half Z size or capsule half height. Invalid for sphere and static mesh.
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "MobSkillCollision|Shape")
	float HalfSizeZ = 16.f;

	// Static mesh resource. Only for static mesh collision.
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "MobSkillCollision|Shape")
	UStaticMesh* CollisionStaticMesh;

public:

	/************** Get functions *****************/

	FORCEINLINE USceneComponent* GetCollisionRoot() { return CollisionRoot; };
	FORCEINLINE UPrimitiveComponent* GetCollision() { return Collision; };
	FORCEINLINE ANaMobSkill* GetSourceSkill() { return SourceSkill; };
	FORCEINLINE FName GetSocketName() { return SocketName; };
	FORCEINLINE FVector GetHalfSize() { return FVector(HalfSizeX, HalfSizeY, HalfSizeZ); };
	FORCEINLINE UStaticMesh* GetCollisionStaticMesh() { return CollisionStaticMesh; };

	/************** Set functions *****************/

	/* Set collision half size.
	* This function doesn't work for static mesh collision. For static mesh please set actor transform directly.
	* @Param InX Box half X size, capsule radius or sphere radius.
	* @Param InY Box half Y size. Invalid for sphere and capsule.
	* @Param InZ Box half Z size or capsule half height. Invalid for sphere.
	*/
	void SetHalfSize(float InX = 8.f, float InY = 8.f, float InZ = 16.f);
	
	/* Set collision half size with vector input.
	* This function doesn't work for static mesh collision. For static mesh please set actor transform directly.
	* InVec.X: Box half X size, capsule radius or sphere radius.
	* InVec.Y: Box half Y size. Invalid for sphere and capsule (just keep default).
	* InVec.Z: InZ Box half Z size or capsule half height. Invalid for sphere (just keep default).
	*/
	void SetHalfSizeVector(FVector InVec = FVector(8.f, 8.f, 16.f)) { SetHalfSize(InVec.X, InVec.Y, InVec.Z); };

	/* Generating */

public:

	/** Make a collision from a skill.
	* @Param SourceSkill The skill owning this collision.
	* @Param Class Applied skill collision class.
	* @Param InTransform Relative transform.
	* @Param AttachToComponent Component this collision should attach. If this param is left null, skill will attach to the root component.
	* @Param SocketName Socket of attachment of this skill.
	* @Param DoAttachment If set false, the skill actor will not attach to anything and generate with world transform.
	*/
	static ANaMobSkillCollision* MakeCollisionByClass(
		ANaMobSkill* SourceSkill,
		TSubclassOf<ANaMobSkillCollision> Class,
		const FTransform & InTranform,
		USceneComponent* AttachToComponent = nullptr,
		FName Socket = NAME_None,
		float LifeSpan = 0.f,
		bool DoAttachment = true
	);

	void Destroyed() override;

	/* Collision detecting */

protected:
	
	// Called when hit detected.
	void SendHit(const FSkillCollisionHitReturn & Data);

	virtual void ConstructHit(FSkillCollisionHitReturn & OutHit, UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, FVector NormalImpulse, const FHitResult & HitResult);
	
	UFUNCTION()
	void SendHitDelegateFunc(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, FVector NormalImpulse, const FHitResult & HitResult);

	TSet<AActor*> AlreadyHitActors;

public:
	
	// If true, the collision will not detect collision to the mob owning it (i.e. source mob of the source mob skill)
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "MobSkillCollision")
	bool bIgnoreSourceMob = true;
};

